### ISSUE TITLE
FoodSearchBar

### ISSUE THREAD

**Issue by jscul** [smcAdvJavaGrp2/MealGuru#12]
Jason, this is probably for you...

I got the search working with the USDA website so nulls aren't an issue. There is an issue with switching databases though... the pop-up won't work if there's text in the text-field.

TEST: search a food in the local database. change to USDA database without deleting "banana". Try searching a different food. It works in most instances except this.

**Comment by JKeirans** [comment]
I added a checkbox but it didn't help things the layout needs a complete rework because IT DOESN'T LOOK GREAT. Also I can't find your problem and the search is really laggy now. I turned off returning objects for the moment. I'll go over it with you later.

**Comment by JKeirans** [comment]
I wonder what the issue is, maybe synchronization? I assume it has to do with the listeners.
