### ISSUE TITLE
Guru Object

### ISSUE THREAD

**Issue by JKeirans** [smcAdvJavaGrp2/MealGuru#18]
Is anyone interested in  creating Strings of help comments to make the program more user friendly. An example of using it is in the SplashGUI. I also need ideas for new behaviors. Explain how to use the program  to someone who has never seen it before. Also if it helps I can make the help comments sequential.

Also there is a compareto method in food that sorts food from healthiest to most unhealthy using a simple heuristic. I was going to add that to the food search bar by adding a sort by button/ or by having the guru store and sort the returned array of food objects and telling the client what the healthiest but there is no room left there. If you can use it for something its there I.E. it returns -1 if the caller is healthier and 1 if the argument is healthier.

The stuff is simple but it seems like magic to people so I thought it would be cool.

**Comment by JKeirans** [comment]
Guru object could not be added to New User Stack Pane without problems, Also it was getting in the way so I turn off click behavior in the secondary Stage. 

I used the splash page as kind of a tutorial, its really rough work and things definitely still need to be tweaked there like putting the "hi user" in a get focused of password instead. 

I think anyone can contribute to this part because the tools are already in the code and so much more can be done with it. 

Also it gets in the way a lot of the time so code needs to be added to make it float away inside the component listeners.

**Comment by ThedaLicious** [comment]
hi sorry i hadn't checked this email prior to last friday

wuTiZzz?

**Comment by JKeirans** [comment]
here sorry for the late reply i have been actively ignoring my phone and
email

**Comment by ThedaLicious** [comment]
hello,

..did u forget to attach it? the tic tac toe?

why have u been actively ignoring yr phone?
...🎅 Duties?

**Comment by ThedaLicious** [comment]
o i sHaAay

**Comment by JKeirans** [comment]
the tictactoe code needs to be fixed, right now the first evaluated spot
always gets returned. I'll work on it tonight if it doesn't get too busy.
merry christmas. Yeah and sorry if I missed some stuff you sent, i was out
of it.

**Comment by ThedaLicious** [comment]
np thank u

happy xmas

**Comment by ThedaLicious** [comment]
pls lmk if when/i am bothering u

**Comment by ThedaLicious** [comment]
r u ok?

y were u "out of it?"

2 MuRCHj AGGNNnaawGGG, AAÁy!?
