### ISSUE TITLE
usda database

### ISSUE THREAD

**Issue by JKeirans** [smcAdvJavaGrp2/MealGuru#2]
Should we combine the databases? If not the folder needs to be rewritten to remove unnecessary parts and make use of ORDER BY. Also the query is missing "Fatty acids, total saturated" and "Fatty acids, total trans".

**Comment by jscul** [comment]
I saw your comments. I've already fixed that.

I didn't use 'ORDER BY'.

Also, be careful of taking String arguments when searching SQL databases...
those apostrophes can cause some confusing errors... solution (escape
characters)

*string = string.replace("'", "''"); *

It reads an apostrophe as an end of an argument...
original string : *WHERE long_desc = 'Aunt marge's cookies'*
*WHERE long_desc = 'Aunt marge' *<- SQL doesn't know what's going on here
*WHERE long_desc = 'Aunt marge''s cookies' *<- good

[image: Inline image 2]

If we combine the data into one database we won't have a consistent
resource database. Meaning... that if a user was to somehow delete the
local database they'd still have the USDA one and that USDA one will be
intact every time they redownload the application (if this was going to be
on the market).

If they deleted the local database we could easily make a new one for them
<https://www.tutorialspoint.com/jdbc/jdbc-create-database.htm> - without
the data of course... I haven't gotten around to doing this.

It may not be hard... if you open up DB Browser for SQLite with our
database it literally gives us all the code we need for making tables...

*CREATE TABLE `DailyIntake` (*
* `id` INTEGER,*
* `user_id` INT NOT NULL,*
* `meal_id` INT NOT NULL,*
* `date` DATE(10) NOT NULL,*
* PRIMARY KEY(`id`),*
* FOREIGN KEY(`user_id`) REFERENCES `User`(`user_id`),*
* FOREIGN KEY(`meal_id`) REFERENCES `Meal`(`meal_id`)*
*);*

**Comment by jscul** [comment]
Seems like italics/pictures don't translate well when contributing to the thread via email.

**Comment by JKeirans** [comment]
The query needs to be fixed to also grab a picture for the food group. the food groups are in foodsearchbar

**Comment by jscul** [comment]
Dude, this is too much for me to do in a day. We still have to make mock
meals and recipes.

The food search bar was working perfectly well with searches. The only
problem was that when you switched the DropDown from USDA to LOCAL or LOCAL
to USDA the pop-up wouldn't work unless you deleted all the text in the
text field.
